server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://my-mysql:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

