
name: dev CI

on:
  pull_request:
    branches: [dev] 
    
jobs:
  build:
  #DD

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Permission
      run: chmod 744 gradlew
      
    - name: Test
      run: ./gradlew test  
