name: Docker Image CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Permission
      run: chmod 744 gradlew
      
    - name : test
      run: ./gradlew clean build
    - name: BUILD
      uses: docker build -t ${{secrets.DOCKER.USERNAME}}/${{secrets.DOCKER.repository}} .  

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKER.USERNAME}}
        password: ${{secrets.DOCKER.PASSWORD}}



